#!/usr/bin/env python3
"""
Item 21 proof skeleton, Lemma B test: is (G, Arf) a complete invariant on the DEGENERATE strata?

Lemma B (radical-FFT) claims: the non-omega data of a 5-config (= the radical rad(omega|_W) beyond the
omega-Gram G) is generated by the Arf invariant of the induced quadratic refinement. Operationally:
fixing G and Arf should determine the orbit. Since (G,R) is a complete invariant (completeness lemma),
this is: does (canon-G, Arf) determine canon-(G,R)?

TEST: dedupe sampled DEGENERATE 5-configs by orbit id = canon-(G,R) [lex-min over S5 vertex perms of
(Gram-bits, RREF of R)]. For each distinct orbit compute (canon-G [lex-min of Gram alone], Arf). Lemma B
<=> the map orbit -> (canon-G, Arf) is INJECTIVE. A COLLISION (two orbits, same canon-G & same Arf,
different R) => Arf does NOT exhaust the non-omega radical data => Lemma B FAILS (more exotic data).

Firewall: this tests SPECIFIC natural data (G, Arf, R), not arbitrary functions -> no over-counting.
Restricted to configs where Arf is defined (intrinsic Q5 exists & descends). n=4 is 100% nondegenerate
(no degenerate stratum) so it is the trivial control. Pure Python; reuses paper22/k6_truncation.make
and m4_cochain.face_arf.
"""
import sys, random
from itertools import combinations, permutations
from collections import defaultdict
sys.path.insert(0, "supplementary/paper22")
sys.path.insert(0, "supplementary/item21_arity5")
from k6_truncation import make
from m4_cochain import face_arf


def k5_sample(N, rng, tries=4000):
    matvec, rank, ker_vec, rand_sym, dm = make(N)
    mats = []
    for _ in range(tries):
        if len(mats) == 5: break
        S = rand_sym(rng)
        if all(rank(dm(S, T)) == N - 1 for T in mats): mats.append(S)
    if len(mats) != 5: return None
    ray = {}
    for i in range(5):
        for j in range(i + 1, 5):
            k = ker_vec(dm(mats[i], mats[j])); ray[(i, j)] = k | (matvec(mats[i], k) << N)
    if len(set(ray.values())) != 10: return None
    return ray   # dict keyed by (i,j)


def rref_tuple(masks, ncols):
    piv = {}
    for m in masks:
        x = m
        for c in sorted(piv, reverse=True):
            if (x >> c) & 1: x ^= piv[c]
        if x:
            c = x.bit_length() - 1
            for cc in list(piv):
                if (piv[cc] >> c) & 1: piv[cc] ^= x
            piv[c] = x
    return tuple(sorted(piv.values()))


def relations(rints, L):
    piv = {}; rels = []
    for i in range(L):
        rv = rints[i]; em = 1 << i
        while rv:
            h = rv.bit_length() - 1
            if h in piv:
                rv ^= piv[h][0]; em ^= piv[h][1]
            else:
                piv[h] = (rv, em); break
        if rv == 0:
            rels.append(em)
    return rels


def f2rank(vs):
    piv = {}
    for v in vs:
        x = v
        while x:
            h = x.bit_length() - 1
            if h in piv: x ^= piv[h]
            else: piv[h] = x; break
    return len(piv)


def canon(ray, N):
    """Return (canonG, orbit_id=(canonGR), dW) under S5 vertex permutations."""
    msk = (1 << N) - 1
    def isymp(u, v):
        return (bin((u & msk) & ((v >> N) & msk)).count('1')
                ^ bin(((u >> N) & msk) & (v & msk)).count('1')) & 1
    slots = list(combinations(range(5), 2))   # 10 pair-slots in fixed order
    L = 10
    bestG = None; bestGR = None
    for sigma in permutations(range(5)):
        rays = [ray[tuple(sorted((sigma[a], sigma[b])))] for a, b in slots]
        G = tuple(isymp(rays[i], rays[j]) for i in range(L) for j in range(i + 1, L))
        if bestG is None or G < bestG:
            bestG = G
        R = rref_tuple(relations(rays, L), L)
        if bestGR is None or (G, R) < bestGR:
            bestGR = (G, R)
    return bestG, bestGR


def run(N, target, seed, budget=150):
    import time
    rng = random.Random(seed); t0 = time.time()
    msk = (1 << N) - 1
    orbits = {}            # orbit_id -> (canonG, Arf)
    got = 0; degen = 0; arfdef = 0
    while got < target and time.time() - t0 < budget:
        ray = k5_sample(N, rng)
        if ray is None: continue
        got += 1
        rays = [ray[(i, j)] for i, j in combinations(range(5), 2)]
        # degenerate? dim W < 2N OR rad>0; here rad>0 <=> dim ker(G) > dim R; simplest: rad via dimW - rankG
        # use: nondeg stratum is (2N,2N,0) i.e. dimW=2N and nondegenerate. Detect rad>0 directly:
        ok, a = face_arf(rays, N)
        # determine rad: dimW and rank of Gram-on-basis
        if not ok:
            continue                        # Arf undefined -> skip (Lemma B is about where Arf exists)
        # degenerate iff dim W < 2N (radical present in W as subspace of F_2^{2N}); also internal rad
        dW = f2rank(rays)
        if dW == 2 * N:
            # could still be nondegenerate(rad=0); these are the omega-only configs, skip for Lemma B
            continue
        degen += 1; arfdef += 1
        cG, cGR = canon(ray, N)
        if cGR in orbits:
            pass
        else:
            orbits[cGR] = (cG, a)
    # injectivity test: do two distinct orbit_ids share (canonG, Arf)?
    bucket = defaultdict(list)
    for oid, (cG, a) in orbits.items():
        bucket[(cG, a)].append(oid)
    collisions = {k: v for k, v in bucket.items() if len(v) > 1}
    # also: does canonG alone already separate orbits? (if yes, Arf adds nothing / test vacuous)
    gbucket = defaultdict(list)
    for oid, (cG, a) in orbits.items():
        gbucket[cG].append(oid)
    g_multi = sum(1 for v in gbucket.values() if len(v) > 1)
    print(f"  n={N}: sampled={got}, degenerate w/ Arf defined={degen}, distinct orbits={len(orbits)}",
          flush=True)
    print(f"    canon-G values with >1 orbit (radical gives multiple orbits per G): {g_multi}"
          f"  (if 0, test is vacuous -- G already separates)", flush=True)
    print(f"    (canon-G, Arf) buckets with >1 orbit [Lemma B COLLISIONS]: {len(collisions)}", flush=True)
    if g_multi == 0:
        print(f"    -> VACUOUS at this sample (canon-G already separates orbits; no radical freedom seen)",
              flush=True)
    elif len(collisions) == 0:
        print(f"    -> Lemma B SUPPORTED: (G,Arf) separates all sampled degenerate orbits "
              f"(Arf resolves the radical freedom).", flush=True)
    else:
        ex = next(iter(collisions.values()))
        print(f"    -> Lemma B FAILS: {len(collisions)} (G,Arf)-collisions -> non-Arf radical data exists "
              f"(more exotic than Arf). e.g. {len(ex)} orbits share one (G,Arf).", flush=True)


if __name__ == "__main__":
    print(__doc__, flush=True)
    print("=== Lemma B: is (G, Arf) complete on the degenerate strata? ===", flush=True)
    run(5, 1500, 22)
    run(6, 1200, 33)
