#!/usr/bin/env python3
"""
Item 21, M5 (sharpened): is the whole invariant ring arity-<=4 on the generic stratum?

M4 generalizes. On the generic stratum (2n,2n,0) the 15 rays span F_2^{2n}, and:

  COMPLETENESS LEMMA. Two labeled ray-tuples (r_i),(r_i') that span, with the SAME ray-Gram G
  (G_ij=omega(r_i,r_j)) and the SAME relation space R={a: XOR_{i in a} r_i = 0}, are Sp-equivalent.
  [Same R => the map r_i|->r_i' is well-defined & linear; same G => it preserves omega; spanning =>
   it is a global element of Sp(2n,F_2).]  Hence (G,R) is a COMPLETE Sp-invariant of the rays, and
  EVERY Sp-invariant is a function of (G,R).

G is arity-<=4 (each entry omega(r_{ij},r_{kl}) touches <= 4 Lagrangians). A tempting "sharpening":
maybe R too is arity-<=4-generated, which would make EVERY invariant reducible. We TEST it and the
test FAILS -- instructively.

Define R4 = span over all 15 four-subsets T={a,b,c,d} of the relations among the 6 rays r_{ij}
(i,j in T). Each such local relation space is a function of 4 Lagrangians => arity-<=4. Always R4 <= R.
The defect dim(R) - dim(R4) measures global (>=5-index) relations not 4-locally generated.

RESULT (the lesson): the defect is NONZERO even at n=4 (where it is 7 = full: NO 4-local relation
exists, all 7 relations are global). But n=4 is SETTLED -- the master theorem gives no H^4 escape
there. So "R is 4-generated" is NOT equivalent to item 21: global relations (= genuine arity-5
invariants) exist even where H^4 is provably 0. Hence the arity-reduction route does NOT decide item
21. Item 21 is the COHOMOLOGICAL statement (the 4-cochain assembled from these is EXACT -- M1 for the
omega-built cochain, M4 for Arf), not "every invariant is arity-<=4". This is another shortcut ruled
out (cf. co_reduce.py), with n=4 as the clean control.

What SURVIVES as a positive: the COMPLETENESS LEMMA is a genuine fragment of M5 -- a first-fundamental-
theorem at the RAY level (ray-invariants are generated by the Gram + the relation space). This script:
  (1) VALIDATES that (G,R) is Sp-invariant (necessary for completeness) via random transvections,
  (2) computes the GLOBAL-RELATION DEFECT dim R - dim R4 per stratum at n=4,5,6 (the ruled-out route).

Pure Python; reuses paper22/k6_truncation.k6.  Also runs the K5 analog (10 rays, four-subset=the
single 4-subset of any 4 of the 5 indices) as a cross-check against XIX's settled n=4 case.
"""
import sys, random
from itertools import combinations
from collections import Counter
sys.path.insert(0, "supplementary/paper22")
from k6_truncation import k6, symp


def basis_of(vs):
    piv = {}
    for v in vs:
        x = v
        while x:
            h = x.bit_length() - 1
            if h in piv: x ^= piv[h]
            else: piv[h] = x; break
    return piv


def f2rank(vs): return len(basis_of(vs))


def relations(rints, support_idx):
    """Relation space (list of basis masks in F_2^{len(rints)}) among rays restricted to support_idx:
    masks a (bits over support_idx) with XOR_{i in a} rints[i] = 0."""
    piv = {}; rels = []
    for i in support_idx:
        rv = rints[i]; em = 1 << i
        while rv:
            h = rv.bit_length() - 1
            if h in piv:
                rv ^= piv[h][0]; em ^= piv[h][1]
            else:
                piv[h] = (rv, em); break
        if rv == 0:
            rels.append(em)
    return rels


def spanrank(masks):
    """F2 rank of a set of integer masks (the dim of the space they span)."""
    piv = {}
    for m in masks:
        x = m
        while x:
            h = x.bit_length() - 1
            if h in piv: x ^= piv[h]
            else: piv[h] = x; break
    return len(piv)


def run(N, target, seed, budget=120):
    import time
    rng = random.Random(seed); t0 = time.time()
    order = [(i, j) for i in range(6) for j in range(i + 1, 6)]
    pair_idx = {p: k for k, p in enumerate(order)}
    nray = 15
    msk = (1 << N) - 1
    def isymp(u, v):
        return (bin((u & msk) & ((v >> N) & msk)).count('1')
                ^ bin(((u >> N) & msk) & (v & msk)).count('1')) & 1
    def transvect(u, vs):                 # T_u(v) = v + omega(v,u) u  (in Sp, preserves omega)
        return [v ^ (u if isymp(v, u) else 0) for v in vs]
    strata = Counter(); defect = Counter(); found = 0
    inv_ok = 0; inv_tested = 0            # (G,R)-invariance validation under random transvections
    while found < target and time.time() - t0 < budget:
        ray = k6(N, rng)
        if ray is None: continue
        found += 1
        rints = [ray[p][0] | (ray[p][1] << N) for p in order]
        dW = f2rank(rints)
        dR = nray - dW
        # R4: relations local to each 4-subset of the 6 Lagrangian indices
        r4 = []
        for T in combinations(range(6), 4):
            supp = [pair_idx[(a, b)] for a, b in combinations(T, 2)]
            r4 += relations(rints, supp)
        dR4 = spanrank(r4) if r4 else 0
        strata[(dW, 2 * N - dW)] += 1
        defect[dR - dR4] += 1
        # VALIDATION that (G,R) is an Sp-invariant (necessary for completeness): apply random
        # transvections (which generate Sp & preserve omega) and confirm G and R are unchanged.
        if found % 5 == 0:
            inv_tested += 1
            tv = rints[:]
            for _ in range(4):
                u = tv[rng.randrange(nray)]
                if u: tv = transvect(u, tv)
            G0 = sorted((i, j, symp(ray[order[i]], ray[order[j]]))
                        for i in range(nray) for j in range(i + 1, nray))
            def symp_int(a, b): return isymp(a, b)
            G1 = sorted((i, j, symp_int(tv[i], tv[j]))
                        for i in range(nray) for j in range(i + 1, nray))
            R0 = spanrank(relations(rints, range(nray)))
            R1 = spanrank(relations(tv, range(nray)))
            if G0 == G1 and R0 == R1:
                inv_ok += 1
    print(f"  n={N}: proper K6 sampled={found}", flush=True)
    print(f"    [validation] (G,R) Sp-invariance under transvections: {inv_ok}/{inv_tested}", flush=True)
    print(f"    strata (dimW, dim radW): {dict(sorted(strata.items(), key=lambda kv:-kv[1]))}", flush=True)
    tot = sum(defect.values())
    print(f"    GLOBAL-RELATION DEFECT dim R - dim R4: {dict(sorted(defect.items()))}", flush=True)
    nz = tot - defect.get(0, 0)
    if set(defect) == {0}:
        print(f"    -> R == R4 on ALL sampled configs: R is arity-<=4-generated here.", flush=True)
    else:
        print(f"    -> R is NOT 4-locally generated on {nz}/{tot} configs (defect>0): the relation space"
              f" carries genuine >=5-index data.", flush=True)
        if N == 4:
            print(f"       *** n=4 is the CONTROL (settled by the master theorem: NO H^4 escape). The"
                  f" defect is nonzero here too -> 'R 4-generated' is NOT equivalent to item 21:"
                  f" global relations = arity-5 invariants exist even where H^4 is provably 0. So the"
                  f" arity-reduction route does NOT decide item 21; item 21 is COHOMOLOGICAL (the"
                  f" assembled 4-cochain is exact, M1/M4), not arity-reducibility. Shortcut ruled out.",
                  flush=True)


if __name__ == "__main__":
    print(__doc__, flush=True)
    print("=== M5 probe: is R arity-<=4-generated? (defect = dim R - dim R4) ===", flush=True)
    run(4, 250, 11)
    run(5, 250, 22)
    run(6, 200, 33)
