"""
Paper VII, Conjecture 4.1 verification.

Two distinct obstruction classes are computed:

  1. Peres-Mermin square (correct source for Conjecture 4.1):
     [f] != 0 in H^2(G_PM, Z/2).
     Verified: XX·ZZ·YY = -I (column 3 product contradicts row products).
     This is Paper III's central extension class.

  2. Full 2-qubit Pauli group P_2-bar:
     Center = Z/4 = {I, -I, iI, -iI}.
     (a) Mod-2 reduction Z/4 -> Z/2: SPLITS (trivial Z/2 component).
     (b) Full Z/4 cocycle: does NOT lift -> [f] != 0 in H^2(G/Z, Z/4).

Conjecture 4.1 uses result (1): the PM-square Z/2 class [f] is the
source-side obstruction.  Since H^2(CP^3, Z/2) = Z/2 = {0, c_1(O(1))},
the pullback Phi^*([f]) != 0 iff Phi is injective on H^2.
"""

import numpy as np
from itertools import product


# =========================================================
# 1. Build the 2-qubit Pauli group
# =========================================================

def pauli_2q():
    """Return 64 elements of P_2-bar as 4x4 matrices."""
    I = np.eye(2, dtype=complex)
    X = np.array([[0,1],[1,0]], dtype=complex)
    Y = np.array([[0,-1j],[1j,0]], dtype=complex)
    Z = np.array([[1,0],[0,-1]], dtype=complex)

    def p1():
        """16 1-qubit matrices."""
        mats = []
        for p in [I, X, Y, Z]:
            for ph in [1, -1, 1j, -1j]:
                mats.append(np.round(ph * p, 12))
        return mats

    mats1 = p1()
    assert len(mats1) == 16

    group = []
    seen = set()
    for ma in mats1:
        for mb in mats1:
            m = np.round(np.kron(ma, mb), 12)
            key = (tuple(m.real.flatten()), tuple(m.imag.flatten()))
            if key not in seen:
                seen.add(key)
                group.append(m)

    assert len(group) == 64, f"Expected 64, got {len(group)}"
    return group


def mult_table(group):
    """Multiplcation table: tbl[i,j] = index of group[i] * group[j]."""
    n = len(group)

    keys = []
    for k in range(n):
        m = group[k]
        keys.append((tuple(m.real.flatten()), tuple(m.imag.flatten())))

    key_to_idx = {k: i for i, k in enumerate(keys)}

    tbl = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            p = np.round(group[i] @ group[j], 12)
            pk = (tuple(p.real.flatten()), tuple(p.imag.flatten()))
            tbl[i, j] = key_to_idx[pk]
    return tbl


# =========================================================
# 2. Find center and build quotient Z_2^4
# =========================================================

def get_center(mult):
    """Return set of center element indices."""
    n = len(mult)
    center = set()
    for i in range(n):
        if all(mult[i, j] == mult[j, i] for j in range(n)):
            center.add(i)
    return center


def quotient_structure(mult, center):
    """Build quotient G/center. Returns coset_of, section, n_cosets."""
    n = len(mult)
    assigned = [False] * n
    coset_of = [-1] * n
    section = {}
    cid = 0

    for i in range(n):
        if assigned[i]:
            continue
        assigned[i] = True
        coset_of[i] = cid
        for c in center:
            ci = mult[i, c]
            if not assigned[ci]:
                assigned[ci] = True
                coset_of[ci] = cid
        section[cid] = i
        cid += 1

    return coset_of, section, cid


# =========================================================
# 3. Check if projective representation lifts
# =========================================================

def check_lift_phases(mult, group, coset_of, section, n_cosets):
    """
    Brute-force check: does there exist phases phi(g) in {±1}
    for the 16 Z_2^4 cosets such that:
        s(a) * s(b) = phi(ab) * s(ab)   (with phi(I)=1)
    for all a,b?

    This tests whether the projective representation of Z_2^4
    generated by Pauli matrices lifts to a linear representation.

    Returns: True if a consistent phase assignment exists (liftable).
    """
    n = len(mult)
    id_el = 0

    # Precompute inv = inverse index
    inv = [-1] * n
    for i in range(n):
        for j in range(n):
            if mult[i, j] == id_el:
                inv[i] = j
                break

    # Compute which pairs anti-commute (for verification)
    def anticommute(a, b):
        """Check if group[a] and group[b] anti-commute: ab = -ba."""
        ab = mult[a, b]
        ba = mult[b, a]
        # ab * ba^{-1} should be -I if anti-commuting
        diff = mult[ab, inv[ba]]
        return np.allclose(group[diff], -np.eye(4))

    # Build the coset multiplication table
    cmult = np.zeros((n_cosets, n_cosets), dtype=int)
    for a in range(n_cosets):
        for b in range(n_cosets):
            cmult[a, b] = coset_of[mult[section[a], section[b]]]

    # Precompute the product deviation: which coset elements multiply
    # to give a non-trivial center element?
    center_coset_of = {}
    for i, c in enumerate(get_center(mult)):
        center_coset_of[c] = coset_of[c]
    # The center elements correspond to cosets 0 and maybe 1+
    # (center is Z_4 with 4 elements)
    center_cosets = set(center_coset_of.values())

    # The obstruction: when we multiply s(a)*s(b), the result
    # differs from s(ab) by a center element.
    # For a lift to exist, we need phases phi such that:
    #   phi(a)*phi(b)*s(a)*s(b) = phi(ab)*s(ab)  (as matrices)

    # Precompute which center elements give which scalars
    center_elements = list(get_center(mult))
    scalar_of = {}
    for i in center_elements:
        m = group[i]
        s = m[0, 0]  # the scalar multiplier (any diagonal entry)
        scalar_of[i] = s

    # Compute the obstruction: when we multiply s(a)*s(b), the result
    # differs from s(ab) by a center element z:
    #   s(a)*s(b) = z * s(ab)    where z in Z(G)
    # The scalar omega(a,b) is z's scalar value (1, -1, i, or -i).
    omega_scalar = np.ones((n_cosets, n_cosets), dtype=complex)
    for a in range(n_cosets):
        for b in range(n_cosets):
            sa, sb = section[a], section[b]
            sab = mult[sa, sb]
            cab = cmult[a, b]
            s_ab = section[cab]
            # diff = sab * inv[s_ab] should be in center
            diff = mult[sab, inv[s_ab]]
            omega_scalar[a, b] = scalar_of[diff]

    # Count non-trivial (non-1) entries
    n_non1 = np.sum(~np.isclose(omega_scalar, 1.0, atol=1e-10))
    print(f"    Center Z(G) has {len(center_elements)} elements")
    print(f"    Center scalars: {set(scalar_of.values())}")
    print(f"    Omega non-trivial entries: {n_non1} / {n_cosets**2}")

    # Distributions of omega values
    unique_s = set(np.round(omega_scalar.flatten(), 10))
    print(f"    Omega takes values: {unique_s}")

    # Check: is the obstruction Z/2-valued or Z/4-valued?
    vals_no_1 = unique_s - {complex(1, 0), complex(1, 0j)}
    z2_obstruction = all(
        np.isclose(v, -1.0, atol=1e-10) or np.isclose(v, complex(1, 0))
        for v in unique_s
    )

    # Now test phase assignments
    # We need phi: Z_2^4 -> {±1, ±i} such that:
    #   phi(a)*phi(b)/phi(ab) = omega_scalar(a,b)
    # where omega_scalar is the scalar value of the center element
    # that s(a)*s(b) differs from s(ab) by.

    print(f"\n    Testing {n_cosets-1} independent phases with ±1...")
    print(f"    Searching 2^{n_cosets-1} = {2**(n_cosets-1)} possibilities...",
          end=" ", flush=True)

    found_lift = False
    for bits in product([1, -1], repeat=n_cosets - 1):
        phi = np.ones(n_cosets, dtype=complex)
        phi[0] = 1
        for i, val in enumerate(bits, start=1):
            phi[i] = complex(val, 0)

        consistent = True
        for a in range(n_cosets):
            if not consistent:
                break
            for b in range(n_cosets):
                expected = phi[a] * phi[b] / phi[cmult[a, b]]
                if not np.allclose(expected, omega_scalar[a, b], atol=1e-10):
                    consistent = False
                    break

        if consistent:
            found_lift = True
            print("FOUND! ✓")
            nz = np.sum(~np.isclose(phi, 1.0, atol=1e-10))
            print(f"    Phase assignment found ({nz} non-trivial phases)")
            break

    if not found_lift:
        print("NONE ✗")
        if z2_obstruction:
            print(f"    Obstruction is Z/2-valued and ±1 phases fail.")
            print(f"    Projective representation DOES NOT LIFT.")
        else:
            print(f"    Obstruction involves ±iI (Z/4 center).")
            # Step A: mod-2 reduction  Z/4 -> Z/2
            # The unique surjective hom Z/4->{±1}:  {1,-1}->+1,  {i,-i}->-1
            # (real scalars stay 1; imaginary scalars -> -1)
            omega_z2 = np.where(
                np.abs(omega_scalar.imag) < 1e-10,   # ±1 (real)
                1.0, -1.0                             # ±i (imaginary) -> -1
            )
            n_nontrivial_z2 = int(np.sum(~np.isclose(omega_z2, 1.0, atol=1e-10)))
            print(f"    Mod-2 reduction: {n_nontrivial_z2}/256 non-trivial entries.")

            # Search ±1 phases for the mod-2-reduced cocycle
            print(f"    Searching ±1 lift for mod-2 omega...", end=" ", flush=True)
            found_z2 = False
            for bits2 in product([1, -1], repeat=n_cosets - 1):
                phi2 = np.ones(n_cosets, dtype=float)
                for i, val in enumerate(bits2, start=1):
                    phi2[i] = val
                ok = True
                for a in range(n_cosets):
                    if not ok:
                        break
                    for b in range(n_cosets):
                        if not np.isclose(phi2[a]*phi2[b]/phi2[cmult[a,b]],
                                          omega_z2[a, b], atol=1e-10):
                            ok = False
                            break
                if ok:
                    found_z2 = True
                    break
            if found_z2:
                print("FOUND ✓  (Z/2 component trivial — splits mod 2)")
            else:
                print("NONE ✗  → [f] ≠ 0 in H²(G/Z, Z/2)  ✓")

            # Step B: search {±1,±i} phases for the full Z/4 cocycle
            # Smart: phi(g)² = omega(g,g) determines whether phi(g) ∈ {±1} or {±i}
            # → only 2^15 possibilities (not 4^15)
            allowed = [[]]   # index 0 = identity, phi(0) = 1 fixed
            impossible = False
            for g in range(1, n_cosets):
                d = omega_scalar[g, g]
                if np.isclose(d, 1.0, atol=1e-10):
                    allowed.append([1.0+0j, -1.0+0j])
                elif np.isclose(d, -1.0, atol=1e-10):
                    allowed.append([1j, -1j])
                else:
                    # omega(g,g) = ±i  =>  phi(g)² = ±i, impossible for {±1,±i}
                    impossible = True
                    break

            if impossible:
                print("    omega(g,g)=±i for some g: no {±1,±i} lift possible")
                found_z4 = False
            else:
                print(f"    Searching {{±1,±i}} lift (2^{n_cosets-1}={2**(n_cosets-1)} "
                      f"constrained possibilities)...", end=" ", flush=True)
                found_z4 = False
                for bits4 in product(range(2), repeat=n_cosets - 1):
                    phi4 = np.ones(n_cosets, dtype=complex)
                    for i, b in enumerate(bits4, start=1):
                        phi4[i] = allowed[i][b]
                    ok = True
                    for a in range(n_cosets):
                        if not ok:
                            break
                        for b in range(n_cosets):
                            if not np.isclose(phi4[a]*phi4[b]/phi4[cmult[a,b]],
                                              omega_scalar[a, b], atol=1e-10):
                                ok = False
                                break
                    if ok:
                        found_z4 = True
                        break
                if found_z4:
                    print("FOUND ✓  (Z/4 extension splits)")
                else:
                    print("NONE ✗  → [f] ≠ 0 in H²(G/Z, Z/4)  ✓")
    else:
        if z2_obstruction:
            print(f"    (Z/2-valued obstruction but phases exist — extension is split)")

    return found_lift


# =========================================================
# 5. Peres-Mermin square: direct Z/2 class verification
# =========================================================

def peres_mermin_square():
    """
    The Mermin magic square (2-qubit observables):

        XI   IX   XX
        IZ   ZI   ZZ
        XZ   ZX   YY

    Row products = I (each row commutes, product = +I).
    Column products: col1=I, col2=I, col3=-I.

    The discrepancy -I is the non-trivial Z/2 class [f] in Paper III.
    This is the correct object for Conjecture 4.1: [f] != 0 in H^2(G_PM, Z/2).
    """
    I = np.eye(2, dtype=complex)
    X = np.array([[0,1],[1,0]], dtype=complex)
    Y = np.array([[0,-1j],[1j,0]], dtype=complex)
    Z = np.array([[1,0],[0,-1]], dtype=complex)

    def kron(A, B):
        return np.kron(A, B)

    square = [
        [kron(X, I), kron(I, X), kron(X, X)],  # row 1
        [kron(I, Z), kron(Z, I), kron(Z, Z)],  # row 2
        [kron(X, Z), kron(Z, X), kron(Y, Y)],  # row 3
    ]

    print("\n  Peres-Mermin magic square (2-qubit):")
    labels = [['XI','IX','XX'], ['IZ','ZI','ZZ'], ['XZ','ZX','YY']]

    # Verify rows and columns all commute within each context
    for r in range(3):
        for i in range(3):
            for j in range(i+1, 3):
                AB = square[r][i] @ square[r][j]
                BA = square[r][j] @ square[r][i]
                assert np.allclose(AB, BA), f"Row {r}: {labels[r][i]},{labels[r][j]} don't commute"
    for c in range(3):
        for i in range(3):
            for j in range(i+1, 3):
                AB = square[i][c] @ square[j][c]
                BA = square[j][c] @ square[i][c]
                assert np.allclose(AB, BA), f"Col {c}: {labels[i][c]},{labels[j][c]} don't commute"
    print("    All within-context pairs commute ✓")

    # Compute row and column products
    print("    Row products:")
    for r in range(3):
        prod = square[r][0] @ square[r][1] @ square[r][2]
        diag = prod[0,0]
        name = "+I" if np.isclose(diag, 1.0) else "-I" if np.isclose(diag, -1.0) else f"{diag}·I"
        print(f"      {' · '.join(labels[r])} = {name}")
        assert np.allclose(prod, np.eye(4)), f"Row {r} product != I"

    print("    Column products:")
    col_signs = []
    for c in range(3):
        prod = square[0][c] @ square[1][c] @ square[2][c]
        diag = np.round(prod[0,0], 10)
        name = "+I" if np.isclose(diag, 1.0) else "-I" if np.isclose(diag, -1.0) else f"{diag}·I"
        print(f"      {labels[0][c]} · {labels[1][c]} · {labels[2][c]} = {name}")
        assert np.allclose(prod, diag * np.eye(4)), f"Col {c} product is not scalar"
        col_signs.append(diag)

    # The global product: all rows = +I, all cols = col1*col2*col3
    global_sign = col_signs[0] * col_signs[1] * col_signs[2]
    print(f"    Global product via columns: {np.round(global_sign, 10)}·I")
    print(f"    Global product via rows:    +I")

    class_nontrivial = not np.isclose(global_sign, 1.0)
    if class_nontrivial:
        print(f"    Contradiction: row-product = +I ≠ col-product = {np.round(global_sign,10)}·I")
        print(f"    → [f] = -1 (generator of Z/2)  ← non-trivial Z/2 class  ✓")
    else:
        print("    No contradiction found — [f] = 0  ✗")
    return class_nontrivial


# =========================================================
# Main
# =========================================================

if __name__ == '__main__':
    print("Paper VII — Conjecture 4.1 Verification")
    print("=" * 60)

    print("\n[1] Building P_2-bar (2-qubit Pauli group)...")
    group = pauli_2q()
    print(f"    {len(group)} elements")

    print("\n[2] Computing multiplication table...")
    mult = mult_table(group)
    print(f"    64x64 table computed")

    print("\n[3] Computing center and quotient...")
    center = get_center(mult)
    print(f"    |Z| = {len(center)}")
    coset_of, section, n_cosets = quotient_structure(mult, center)
    print(f"    |G/Z| = {n_cosets}")
    assert n_cosets == 16

    print("\n[4] Full-group projective lift check (Z/4 structure):")
    print("    NOTE: full P_2-bar center is Z/4; mod-2 reduction of the full")
    print("    cocycle may split even when the Z/4 extension does not.")
    print("    This tests H^2(G/Z, Z/4), not Paper III's H^2(G_PM, Z/2).")
    liftable = check_lift_phases(mult, group, coset_of, section, n_cosets)

    print()
    if not liftable:
        print("    Full Z/4 extension does not split (H^2(G/Z,Z/4) non-trivial).")
    else:
        print("    Full extension splits.")

    print("\n[5] Peres-Mermin square: direct Z/2 class [f] verification")
    print("    (This is the correct object for Conjecture 4.1)")
    pm_nontrivial = peres_mermin_square()

    print()
    print("=" * 60)
    print("Conclusions:")
    print(f"  H^2(G/Z, Z/4) non-trivial:           {'YES' if not liftable else 'NO'}")
    print(f"  H^2(G/Z, Z/2) mod-2 component:       see step [4] above")
    print(f"  [f] != 0 in H^2(G_PM, Z/2) [Paper III]:  {'YES' if pm_nontrivial else 'NO'}")
    if pm_nontrivial:
        print()
        print("  Since H^2(CP^3, Z/2) = Z/2 has exactly one non-zero class,")
        print("  Conjecture 4.1 reduces to: Phi^*([f]) != 0.")
        print("  Source-side non-vanishing: CONFIRMED by PM square.")
        print()
        print("  Conjecture 4.1 (simplified): source [f] != 0  ✓")
        print("  Pullback Phi^*([f]) != 0: depends on Phi being injective on H^2.")
        print("  (This remains the conjectural step.)")
    print("=" * 60)
